const CONSTANTS = {
  SOCKET_SERVER_EVENTS: {
    NEW_MESSAGE: 'NEW_MESSAGE',
    NEW_MESSAGE_SUCCESS: 'NEW_MESSAGE_SUCCESS',
    NEW_MESSAGE_ERROR: 'NEW_MESSAGE_ERROR',
    JOIN_ROOM: 'JOIN_ROOM',
    LEAVE_ROOM: 'LEAVE_ROOM',
    MESSAGE_IN_ROOM: 'MESSAGE_IN_ROOM',
  },
};

module.exports = CONSTANTS;
